README.md

This PR updates the README with configuration instructions and expands on the installation instructions. 
The installation instructions will need to be updated and Confluent Cloud added as an option once the connector is available on Confluent Hub.

DOC-303: Update README with configuration properties and installation instructions

---

pom.xml

We were using a very old version of the parent POM, fixed in https://github.com/ably/kafka-connect-ably/commit/7e82474757a467f0e6c18f855ea082c79efd79cb.
Also, not sure, but https://github.com/ably/kafka-connect-ably/commit/1bc2e9318cc7da4e29453f6385bd0919e9455bf3 may have helped.
Now seeing a different build failure with Maven 3.8.1 `mvn clean package` on my local macOS machine:
```
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.ably.kafka.connect.DocumentationTest
[ERROR] Tests run: 13, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 21.802 s <<< FAILURE! - in com.ably.kafka.connect.DocumentationTest
[ERROR] rstConfigProviders  Time elapsed: 3.214 s  <<< ERROR! …
```

Fix build failure relating to Kafka Connect parent POM

---

.github/workflows/integration-test.yml

Initial prototype: https://github.com/ably/ably-asset-tracking-android/pull/441
See [this internal Slack thread](https://ably-real-time.slack.com/archives/CF7GGBF2N/p1631814436061500) for more context.

Explicitly specify workflow `permissions` required to succeed when our org switches default access from 'permissive' to 'restricted'

---

pom.xml
src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java
src/test/java/com/ably/kafka/connect/AblyHelpers.java

So we can track the usage of the connector.
`kafka-connect-ably` has been added to agents.json in https://github.com/ably/ably-common/pull/123.

Set 'kafka-connect-ably' in the Ably-Agent header

---

src/main/java/com/ably/kafka/connect/ChannelSinkTask.java

This PR fixes an issue where a failure of message delivery would cause the whole task to halt.
Changes
* If queueMessages is enabled and if an AblyException occurs, I log error
* If queueMessages is not enabled I thrown RetriableException (See `put` https://kafka.apache.org/11/javadoc/org/apache/kafka/connect/sink/SinkTask.html for why I did that)

Caught exception and printed stack trace instead of throwing it to resume task

---

README.md

This PR updates the README with instructions for installing the Ably Kafka Connector from Confluent Hub. There are two methods for doing so:
* Use the Confluent Hub Client and run the install command.
* Download the connector zip directly from Confluent Hub rather than building it directly from this repository.

Update README with instructions for installing from Confluent Hub

---

src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java
src/main/java/com/ably/kafka/connect/ChannelSinkMapping.java
src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
src/main/java/com/ably/kafka/connect/DefaultChannelSinkMapping.java
src/test/java/com/ably/kafka/connect/DefaultChannelSinkMappingTest.java

This pull request aims to refactor the way sink record maps to Ably channels. Record to channel mapping is currently based on a static configuration and as design imposes, it can only allow a single channel. I have refactored how the channel is provided to a 'sink task'  so that it is possible now to provide an Ably channel-per record. However because of the current implementation, the functionality will not change and we will still have a single channel throughout app lifecycle. This is just a ground work that allows us to provide a channel per record more easily. Following PRs should make the aim of this one more clear. I will try to summarise work done below
* Added an interface to map between `SinkRecord` and an Ably `Channel` so that channel mapping happens through a common interface …

Refactor to channel map interface

---

README.md
src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java
src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
src/main/java/com/ably/kafka/connect/DefaultChannelSinkMapping.java
src/main/java/com/ably/kafka/connect/MessageSinkMapping.java
src/test/java/com/ably/kafka/connect/MessageSinkMappingTest.java

This PR adds a new optional configuration property to set message name with interpolation support.
Closes https://github.com/ably/kafka-connect-ably/issues/46

Make message name configurable

---

src/main/java/com/ably/kafka/connect/ChannelConfig.java
src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
src/main/java/com/ably/kafka/connect/DefaultChannelConfig.java
src/main/java/com/ably/kafka/connect/DefaultChannelSinkMapping.java
src/test/java/com/ably/kafka/connect/DefaultChannelSinkMappingTest.java

This PR addresses https://github.com/ably/kafka-connect-ably/issues/44 raised by @QuintinWillison and creates a separate channel configuration class to retrieve channel related configuration values. 
Closes https://github.com/ably/kafka-connect-ably/issues/44

Refactor channel configuration logic

---

README.md
src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java

This PR removes `client.recover` property from configuration. As suggested by @lmars

Remove recover config

---

README.md
src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java

This PR removes `client.use.binary.protocol` from connector and Readme.
Discussed with @SimonWoolf and captured with https://github.com/ably/ably-java/issues/758
Two reasons
* The way ably-java handle this option
* This was a property developed for clients who can't handle binary which is not the case for our conector
Closes https://github.com/ably/kafka-connect-ably/issues/57

Remove client.use.binary.protocol

---

docker-compose.yml
src/main/java/com/ably/kafka/connect/client/DefaultAblyClientFactory.java
src/main/java/com/ably/kafka/connect/mapping/DefaultChannelSinkMapping.java
src/test/java/com/ably/kafka/connect/DefaultChannelSinkMappingTest.java

This PR exposes Kafka connect advertised listener ports so that listeners outside of Docker could produce / consume messages

Update Kafka advertised listeners and expose ports

---

pom.xml

Update ably-java to fix a potential vulnerability issue raised with [this internal Slack message](https://ably-real-time.slack.com/archives/C01KS2Q8NN7/p1662720333537259)
> We have identified a vulnerability with the Ably connector. We are working with our tech partners on aggressively fixing the vulnerabilities. Could you please help us fix vulnerabilities as soon as possible? We ran the trivy(https://github.com/aquasecurity/trivy) scanner to identify them.
> PartnerName: ably
> ConnectorName: ably-kafka-connect-ably
> ConnectorVersion: 2.0.1
> VulnerabilityID: CVE-2020-11050
> PkgName: org.java-websocket:Java-WebSocket
> PkgPath: Java-WebSocket-1.4.0.jar
> InstalledVersion: 1.4.0
> FixedVersion: 1.5.0
> Severity: HIGH
> CVSS: 8.1
> Title: java-websocket: WebSocketClient does not perform …

Update ably-java version to 1.2.16

---

pom.xml

This PR removes jackson-mapper dependency that has vulnerability.
After all this dependency wasn't necessary and was scoped to tests.
Closes https://github.com/ably/kafka-connect-ably/issues/91

Remove jackson-mapper-asl dependency 

---

docker-compose-distributed.yml
docker-compose.yml

This PR updates Docker image versions on docker-compose files to their latest version
It also replaces deprecated `cp-enterprise-kafka ` with `cp-server`
Closes https://github.com/ably/kafka-connect-ably/issues/81

Update docker images in docker-compose files

---

README.md
src/main/java/com/ably/kafka/connect/config/ConfigValueEvaluator.java
src/main/java/com/ably/kafka/connect/utils/RecordHeaderConversions.java
src/test/java/com/ably/kafka/connect/ConfigValueEvaluatorTest.java
src/test/java/com/ably/kafka/connect/utils/RecordHeaderConversionsTest.java

Adds support for string key for both when creating headers and interpolating for configuration values.
This also removes force cast to byte[] to prevent any crash if key schema is different and instead skips processing the key.
Closes https://github.com/ably/kafka-connect-ably/issues/98

Add string key support

---

generate_changelog.sh
src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
src/main/java/com/ably/kafka/connect/SuspendQueue.java
src/main/java/com/ably/kafka/connect/client/AblyClient.java
src/main/java/com/ably/kafka/connect/client/DefaultAblyClient.java
src/main/java/com/ably/kafka/connect/client/SuspensionCallback.java
src/test/java/com/ably/kafka/connect/ChannelSinkTaskTest.java
src/test/java/com/ably/kafka/connect/SuspendQueueTest.java
src/test/java/com/ably/kafka/connect/fakes/FakeAblyClient.java
src/test/java/com/ably/kafka/connect/fakes/FakeClientFactory.java
src/test/java/com/ably/kafka/connect/fakes/RandomConnectionStateChanger.java

Add an intermediate queue to re-publish messages that were failed because of connection going into suspended state.
Fixes https://github.com/ably/kafka-connect-ably/issues/106

Add suspend queue 

---

Dockerfile
pom.xml
src/main/java/com/ably/kafka/connect/mapping/ChannelSinkMapping.java

This gets the build instructions in the README working again.
This removes errors about missing javadoc comments, as it seems we've fallen way behind on this anyway. If the team want to restore that lint check, a PR will be needed to add the missing docs and re-enable it.
Also updating the Docker build base image to match the min java requirement, as compilation within the container now fails as it's still running Java 11.
Fixing the one legit javadoc error on `ChannelSinkMapping`, as this can no-longer throw `AblyException` since the signature change and no `AblyRealtime` client is provided anymore.

Fix Docker build errors

---

Dockerfile
Dockerfile_development
docker-compose-distributed.yml
docker-compose.yml
pom.xml
src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
src/main/java/com/ably/kafka/connect/mapping/ChannelSinkMapping.java

This updates the docker images we're using to the latest version of Confluent Platform.
The 6.0 release we used previously comes with Java 8, so the latest code wouldn't work.
This release distributes with Java 11. Later versions are supported but you have to modify the image yourself to do this. There's one change needed to `ChannelSinkTask` to be Java 11 compatible included here.

Update to Confluent Platform 7.4.0

---

docker-compose.yml
src/main/java/com/ably/kafka/connect/ChannelSinkConnector.java

Closes #138 
Setting `max.tasks` to any value >= 1 previously made no difference to the number of tasks running, you'd always just get a single task. This is because we only ever returned a single config instance, no-matter how many tasks were being requested as a maximum by the Connect framework. More details in ticket #138

Support multiple tasks

---

README.md

Adds steps to use the Connector as a "Bring Your Own Connector" on Confluent Cloud.

docs: readme entry for Confluent Cloud BYOC

---

README.md

Confluent currently refer to what was BYOC as [Custom Connectors](https://docs.confluent.io/cloud/current/connectors/bring-your-connector/overview.html) now, so this changes the language to match in our README.

Chance BYOC references to Custom Connector

---

README.md

For Confluent, these elements need to be specified if you're using datagen to put data in.
Using REST and the UI also both work with these options so adding this in seems to be the most robust way to get someone started.

Include converters + schema disable by default in docs for Confluent

---

src/main/java/com/ably/kafka/connect/utils/RecordHeaderConversions.java
src/test/java/com/ably/kafka/connect/MessageConversionTest.java

This PR fix two problems with Kafka headers:
* When the message reaches our Kafka Connector that contains headers, Kafka automatically deserialises those headers. Because Kafka doesn't know about what types things were originally, things just get deserialised to the most obvious type. So that means numeric strings end up as a numbers. There’s a problem with Realtime whereby large numbers in headers breaks things.
* headers shouldn’t be in `extras.kafka.headers` but instead simply in `extras.headers` - the former screws around with other things.

feat!: stringify and flatten Kafka headers in extras

---

pom.xml

Resolves #186 
Updates `ably-java` dependency, in new `ably-java` release Rest client sends `clientId` according to specification

chore: upgrade `ably-java` dependency

---

src/main/java/com/ably/kafka/connect/offset/OffsetRegistryService.java
src/test/java/com/ably/kafka/connect/AblyBatchClientTest.java
src/test/java/com/ably/kafka/connect/offset/OffsetRegistryServiceTest.java

Set topic partitions offsets to the end of logs.
Issue:  https://github.com/ably/kafka-connect-ably/issues/193

fix: commit topic partitions end offsets
