src/main/java/com/ably/kafka/connect/ChannelSinkConnector.java, src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java, src/main/java/com/ably/kafka/connect/ChannelSinkTask.java
I've refactored the project code according to [those suggestions from a Slack discussion](https://ably-real-time.slack.com/archives/C01KS2Q8NN7/p1628254770021800)
I've tried to put each suggestion into a separate commit so you could try reverting some of them if you don't like the change I've made :wink:
Closes #11 #12 #16.
=> Refactor project code

src/main/java/com/ably/kafka/connect/ChannelSinkTask.java, src/main/java/com/ably/kafka/connect/MessageSinkMapping.java, src/test/java/com/ably/kafka/connect/MessageSinkMappingTest.java
This PR refactors message mapping logic.
closes https://github.com/ably/kafka-connect-ably/issues/41
=> Refactor sink to message mapping

pom.xml
This PR updates language level to 9 so that I can use it with IntelliJ IDE. I wanted to keep this change out of other PRs as it's not very relevant to any of them
=> Update language target to 9 to work with IntelliJ

COPYRIGHT, src/test/java/com/ably/kafka/connect/ChannelSinkTaskIT.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkTaskTest.java
This PR contains integration tests for 
* Static and pattern based channel tests
* Static and pattern based message tests
=> Integration tests for static and pattern based mapping

src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java, src/test/java/com/ably/kafka/connect/ChannelSinkConnectorIT.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkConnectorTest.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkTaskTest.java
This PR should fix https://github.com/ably/kafka-connect-ably/issues/34
It also contains some integration tests for the connector including verification of the fix to this issue. 
It also removes an unneccessary header from a test file 
Closes https://github.com/ably/kafka-connect-ably/issues/34
Note to reviewers -> Currently the integration tests for our connector is restricted as I realised that we do not actually have validators for our own configurations. I will add more integration tests when after validators are added
=> NPE on proxy port issue and some integration tests for connector

.editorconfig, src/main/java/com/ably/kafka/connect/ChannelSinkConnectorConfig.java
This is a cleanup PR intended to cleanup the config class before adding functional changes
* I added a .editorconfig file from https://github.com/ably/ably-java/blob/main/.editorconfig
* Header from `ChannelSinkConnectorConfig` is removed
* Reformatted `ChannelSinkConnectorConfig` 
No functional change is expected from this PR
=> Add editorconfig and do some formatting

src/test/java/com/ably/kafka/connect/AblyHelpers.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkTaskTest.java
This PR improves Integration test performance by reusing some objects for all tests
=> Optimise integration tests

src/main/java/com/ably/kafka/connect/ChannelSinkConnector.java, src/main/java/com/ably/kafka/connect/ChannelSinkTask.java, src/main/java/com/ably/kafka/connect/ClientOptionsLogHandler.java, src/main/java/com/ably/kafka/connect/client/AblyClient.java, src/main/java/com/ably/kafka/connect/client/AblyClientFactory.java, src/main/java/com/ably/kafka/connect/client/DefaultAblyClient.java, src/main/java/com/ably/kafka/connect/client/DefaultAblyClientFactory.java, src/main/java/com/ably/kafka/connect/config/ChannelConfig.java, src/main/java/com/ably/kafka/connect/config/ChannelSinkConnectorConfig.java, src/main/java/com/ably/kafka/connect/config/ConfigValueEvaluator.java, src/main/java/com/ably/kafka/connect/config/DefaultChannelConfig.java, src/main/java/com/ably/kafka/connect/mapping/ChannelSinkMapping.java, src/main/java/com/ably/kafka/connect/mapping/DefaultChannelSinkMapping.java, src/main/java/com/ably/kafka/connect/mapping/DefaultMessageSinkMapping.java, src/main/java/com/ably/kafka/connect/mapping/MessageSinkMapping.java, src/main/java/com/ably/kafka/connect/mapping/MessageSinkMappingImpl.java, src/main/java/com/ably/kafka/connect/utils/ByteArrayUtils.java, src/main/java/com/ably/kafka/connect/utils/ClientOptionsLogHandler.java, src/main/java/com/ably/kafka/connect/utils/KafkaExtrasExtractor.java, src/test/java/com/ably/kafka/connect/ConfigValueEvaluatorTest.java, src/test/java/com/ably/kafka/connect/DefaultChannelSinkMappingTest.java, src/test/java/com/ably/kafka/connect/MessageSinkMappingTest.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkConnectorTest.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkTaskTest.java
This PR contains some structure and code reorganisation, including refactoring and fixing some issues with ChannelSinkTask
* Remove unnecessary headers and commentary
* Update the project packaging for better organisation
* Create a log handler class and move log handling business to it
* Decouple Ably client from task and create a separate interface for Ably client functions for testability and better maintainability.
=> Code reorganisation and refinement

README.md
Update readme to emphasize n-n mapping
Closes https://github.com/ably/kafka-connect-ably/issues/66
=> Update readme to emphasize n-n mapping

.github/workflows/integration-test.yml
AWS credentials actions for OIDC
Closes https://github.com/ably/kafka-connect-ably/issues/72
=> AWS action for OIDC

src/main/java/com/ably/kafka/connect/utils/StructToJsonConverter.java, src/test/java/com/ably/kafka/connect/utils/StructToJsonConverterTest.java
Fixes https://github.com/ably/kafka-connect-ably/issues/86
=> Fix NullPointerException issue when null struct value is provided to Json converter

src/main/java/com/ably/kafka/connect/ChannelSinkTask.java, src/main/java/com/ably/kafka/connect/utils/KafkaExtrasExtractor.java
I removed some logs which I thought wasn't that necessary and was creating some noise
=> Remove some unneccessary logging code

pom.xml
Update ably-java version to 1.2.25
=> Update ably java version

loadtest/Pipfile, loadtest/Pipfile.lock, loadtest/README.md, loadtest/loadgen/consumer.py, loadtest/loadgen/data.py, loadtest/loadgen/main.py, loadtest/loadgen/producer.py, loadtest/loadgen/schema.py
This is a Python app I've written to help generate some test data and ensure everything is coming through to Ably as expected. It's not really intended to be part of the connector test suite, but I've found it useful for measuring throughput and testing deployments.
I'll leave it on this branch as a PR for now - we can consider merging it if others find it helpful
=> End to end testing

README.md
This better focuses the Ably blurb to match our current positioning and customers, as requested by Andra.
=> Update Ably blurb in README

src/main/java/com/ably/kafka/connect/mapping/MessageConverter.java, src/main/java/com/ably/kafka/connect/utils/RecordHeaderConversions.java, src/main/java/com/ably/kafka/connect/utils/SpecialAblyHeader.java, src/test/java/com/ably/kafka/connect/mapping/MessageConverterTest.java, src/test/java/com/ably/kafka/connect/utils/MockedHeader.java, src/test/java/com/ably/kafka/connect/utils/RecordHeaderConversionsTest.java, src/test/java/com/ably/kafka/connect/utils/StructToJsonConverterTest.java
Fixes https://github.com/ably/kafka-connect-ably/issues/158
Resolves [SDK-3891](https://ably.atlassian.net/browse/SDK-3891)
[SDK-3891]: https://ably.atlassian.net/browse/SDK-3891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: encoding for Ably Message using special Kafka header

README.md
* clarify where to look for AWS MSK zip 
* add client.environment to property table
=> docs: clarify where to look for AWS MSK zip

README.md
Added some tweaks to Confluent Cloud instruction
=> docs: clarify Confluent Cloud setup

examples/msk_connect/README.md
=> Update AWS MSK download link to latest version

CHANGELOG.md, pom.xml
Kafka connector release `v4.1.1`
=> Release v4.1.1

.github/workflows/integration-test.yml, Dockerfile, pom.xml, src/main/resources/META-INF/services/org.apache.kafka.connect.sink.SinkConnector, src/test/java/com/ably/kafka/connect/integration/ChannelSinkConnectorTest.java, src/test/java/com/ably/kafka/connect/integration/ChannelSinkTaskTest.java, src/test/resources/META-INF/services/org.apache.kafka.connect.storage.Converter
* bump dependencies to the latest 3.x
* reverted embedded cluster settings workaround
* updated Docker settings
=> chore: bump dependencies to the latest 3.x

CHANGELOG.md, examples/msk_connect/README.md, pom.xml
=> Release 4.1.2
